apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
  name: argo-rollouts
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts
  template:
    metadata:
      namespace: codefresh-dev
      labels:
        app.kubernetes.io/name: argo-rollouts
      annotations:
        ad.datadoghq.com/argocd-rollouts.check_names: |-
          ["openmetrics"]
        ad.datadoghq.com/argocd-rollouts.init_configs: |-
          [{}]
        ad.datadoghq.com/argocd-rollouts.instances: |-
          [
            {
              "openmetrics_endpoint": "http://argo-rollouts-metrics.codefresh-dev:8090/metrics",
              "namespace": "codefresh-dev",
              "metrics": [".*"]
            }
          ]~/src/dev-runtime (main)
